Objetivo 0
MauronMP/PMP_IV pull request #2
Opened 2022-09-16 07:34 UTC by MauronMP

Pull request del repositorio de Pablo Morenilla Pinos

2022-09-16 11:24 UTC, MauronMP reviewed
Actulizado

2022-09-18 16:06 UTC, JJ requested changes
El problema no está muy claro (porque no está claro quién es el cliente) y no hay una lógica de negocio aceptable.

2022-09-18 16:06 UTC, JJ commented on README.md
> +Actualmete existen muchas empresas que tienen comedores y espacios habilitados con menús para los trabajadores, pero no suelen tener en cuenta
typo

2022-09-18 16:06 UTC, JJ commented on README.md
> +que exiten gente alergena a distintos alimentos, enfermedades, etc. En este caso se quiere tratar con las personas celiacas.
typos

2022-09-18 16:06 UTC, JJ commented on README.md
> +para poder incluir en los menús de las empresas o por otro lado para usuarios normales.
Catálogo es literalmente un directorio donde se buscan cosas. Por favor, miran las lógicas de negocio aceptables.

2022-09-19 12:30 UTC, MauronMP commented on README.md
> +para poder incluir en los menús de las empresas o por otro lado para usuarios normales.
Buenas tardes, he actualizado el README.md con una idea distinta, un saludo

2022-09-19 12:55 UTC, JJ requested changes
Por favor, formula correctamente el problema; sin una formulación clara, es imposible saber si se ha resuelto (y por tanto no se puede testear, no se pueden escribir historias de usuario...)

2022-09-19 12:55 UTC, JJ commented on README.md
> +    La idea principal a tratar sería la gestión, coordinación y planificación de un gimnasio.
No es un problema. Si no es un problema, el resto de lo que digas no es válido. Os expliqué la metodología de design thinking, lo hice para algo. En las tres fases te pueden ayudar a formular correctamente un problema a partir de entender al cliente.

2022-09-19 14:55 UTC, MauronMP commented on README.md
> +    La idea principal a tratar sería la gestión, coordinación y planificación de un gimnasio.
Buenas tardes, he reformulado el problema a tratar, creo que no me había explicado correctamente, ahora he seguido las tres fases, un saludo.

2022-09-19 15:50 UTC, JJ requested changes
Mientras que nos podemos quedar con el gimnasio, deberías hablar con la gente que lo lleve a ver qué problemas tiene y si hay alguno que tengan que hacer cálculos complicados o lo que sea y que necesiten una aplicación que lo resuelva.

2022-09-19 15:50 UTC, JJ commented on README.md
> +    Siguiendo el "desing-thinking" para poder diseñar una aplicación desde 0, se ven los 3 puntos principales a tratar:
*design*

2022-09-19 15:50 UTC, JJ commented on README.md
> +    Planificación y organización de un gimnasio de cara a los usuarios.
Revisa el concepto de empatizar. Implica ponerte en el lugar del cliente o clientes. Aquí ni siquiera concretas el cliente. Y "planificación" no es un problema.

2022-09-19 15:50 UTC, JJ commented on README.md
> +    El cliente final, recibe una planificación y gestión de sus rutinas, dietas, actividades también teniendo en cuenta las tarifas que paga.
Para que sea válido el problema, tiene que poder testearse automáticamente (vamos a hacerlo en el objetivo 3), es decir, tiene un programa ser capaz de decir si el comportamiento que tiene el programa resuelve el problema o no. ¿Eres capaz de codificar esto?
En todo caso, ni defines qué significa "planificación", ni defines cuál es el problema de "gestión" de un gimnasio, ni en general parece que estés aplicando correctamente ni entendiendo estos conceptos. Si la presentación no es suficiente, por favor consulta algún texto sobre design thinking o tutorial en internet.

2022-09-19 15:50 UTC, JJ commented on README.md
> +    Si, llevo entrenando dos años y tengo conocimientos de los distintos perfiles de usuarios que pueden darse, sus condiciones y posibilidades.
¿Y has hablado con la gente del gimnasio a ver qué problemas tiene?

2022-09-20 11:59 UTC, MauronMP commented on README.md
> +    Si, llevo entrenando dos años y tengo conocimientos de los distintos perfiles de usuarios que pueden darse, sus condiciones y posibilidades.
Buenas, he preguntado esta mañana a la dueña del gimnasio, me ha contado que si tiene un problema a resolver, en el readme lo indico.

2022-09-20 15:24 UTC, JJ commented on README.md
> +    Esto asegura la dueña que le resultaría útil, puesto que de esta manera los monitores del gimnasio estarían enfocados en los clientes, comprobando que vayan al ritmo de la sesión, realicen bien l
¿De qué sirve que esto esté en la nube? ¿No puede ser un ordenador normal con varias pantallas conectadas?

2022-09-20 15:54 UTC, MauronMP commented
Buenas tardes, respondiendo a las preguntas:

**- ¿Es un problema combinar los ejercicios? ¿Tienen que usar una secuencia determinada?** 

Respondo estas dos seguidas, puesto que, dependiendo de las sesiones a las que estén enfocadas, la combinación de ejercicios varía, es decir, si la sesión está enfocada en el tren superior, debe de realizarse con una secuencia en la que no se sobrecarga una misma zona muscular de manera seguida, debe de haber otro ejercicio entre ambos que no trate esa misma zona. Por otro lado, la combinación de ejercicios y la intensidad no puede ser la misma para un grupo específico, si son para personas de edad avanzada, deben de ser de intensidad baja y presenten poca carga, pero al mismo tiempo enfoquen toda la zona a entrenar. De igual modo, por ejemplo, pueden ser sesiones de rehabilitación. Este tipo de sesiones, deben de seguir un patrón adecuado y no aleatorio

**- ¿Hay que usar algún algoritmo para hacerlo satisfactoriamente?**

Aquí no sabría responderle con exactitud, puesto que tendría que mirarlo con más detalle.

 **- ¿De qué sirve que esto esté en la nube? ¿No puede ser un ordenador normal con varias pantallas conectadas?**

En el caso del centro al que he preguntado no, ya que tienen varias zonas aisladas una de otra en distintas plantas con distintos tipos de sesiones, todas sus pantallas están directamente conectadas a su red y tiene varios gimnasios en el mismo pueblo.

2022-09-20 18:32 UTC, JJ commented
> Buenas tardes, respondiendo a las preguntas:
> 
> **- ¿Es un problema combinar los ejercicios? ¿Tienen que usar una secuencia determinada?**
> 
> Respondo estas dos seguidas, puesto que, dependiendo de las sesiones a las que estén enfocadas, la combinación de ejercicios varía, es decir, si la sesión está enfocada en el tren superior, debe de realizarse con una secuencia en la que no se sobrecarga una misma zona muscular de manera seguida, debe de haber otro ejercicio entre ambos que no trate esa misma zona. Por otro lado, la combinación de ejercicios y la intensidad no puede ser la misma para un grupo específico, si son para personas de edad avanzada, deben de ser de intensidad baja y presenten poca carga, pero al mismo tiempo enfoquen toda la zona a entrenar. De igual modo, por ejemplo, pueden ser sesiones de rehabilitación. Este tipo de sesiones, deben de seguir un patrón adecuado y no aleatorio

Hola, Pablo. Mira, hoy tenía gimnasio y le he preguntado al entrenador. Me ha contado más o menos lo que dices, salvo que como se hace sobre todo entrenamiento funcional lo que hacen es que cada uno tienen una serie de ejercicios y rutinas, con su progresión, que van variando. Si alguno pide adaptación (como yo, que suelo pedirla), cambian un grupo muscular por otro. Los ejercicios se los saben, y no tienen que realizar ningún cálculo complicado para eso; se conocen las secuencias.
> 
> **- ¿Hay que usar algún algoritmo para hacerlo satisfactoriamente?**
> 
> Aquí no sabría responderle con exactitud, puesto que tendría que mirarlo con más detalle.

Ya te digo yo por lo que me ha dicho el entrenador: no. Las progresiones de grupos musculares saben más o menos como son, y son sota caballo y rey. Las combinaciones y repeticiones también, y las progresiones son muy simples. Le he preguntado si tenían que hacer algún tipo de cálculo por afinidad entre grupos musculares, lo de lo que fuera, yo qué sé, medir esfuerzo en cada ejercico y que cambie más de un 30% (por decirte algo) y no. Simplemente se conocen las combinaciones de ejercicios, los varían con cierta frecuencia, y ya. 
> 
> **- ¿De qué sirve que esto esté en la nube? ¿No puede ser un ordenador normal con varias pantallas conectadas?**
> 
> En el caso del centro al que he preguntado no, ya que tienen varias zonas aisladas una de otra en distintas plantas con distintos tipos de sesiones, todas sus pantallas están directamente conectadas a su red y tiene varios gimnasios en el mismo pueblo.

Entonces, blanco y en botella. De veras que yo creo que en el tema de ejercicios no hay mucha tela que cortar, o ninguna. Lo siento.

2022-09-20 19:02 UTC, MauronMP commented
De acuerdo, pensaré en otra idea, perdone y gracias

2022-09-20 21:03 UTC, MauronMP commented
Buenas, he cambiado la idea

2022-09-21 07:50 UTC, JJ commented
Por favor, pon la lista de comprobación en el cuerpo del PR.

2022-09-21 08:01 UTC, JJ approved these changes
Con muchas precauciones, lo voy a dar por aprobado.

2022-09-21 08:01 UTC, JJ commented on README.md
> +    Si, se ha configurado correctamente con la clase de SSH
No, esto no lo has hecho o no lo has enlazado. Me voy a creer que lo has hecho, pero por favor mira lo que respondes antes de responderlo.

2022-09-21 15:07 UTC, MauronMP commented
Buenas tardes, he subido otra idea en caso de que la primera no sea viable o tenga más dificultad, igualmente en las clases le quiero comentar varias cosas que he visto al respecto de la primera idea de predecir incendios.

2022-09-21 15:13 UTC, JJ commented
Si has puesto una nueva idea por las precauciones que se han indicado, :clap: . Si no, la idea original es la aceptada. Así que cuidado...

2022-09-21 15:26 UTC, MauronMP commented
Sí, he puesto la segunda idea en caso de que no vea viable la primera ideas una vez le explique lo que he estado viendo.
En caso de que no lo fuera, ¿la segunda idea que le he adjuntado sería correcta?
Gracias.

2022-09-21 15:44 UTC, JJ commented
> Sí, he puesto la segunda idea en caso de que no vea viable la primera ideas una vez le explique lo que he estado viendo. En caso de que no lo fuera, ¿la segunda idea que le he adjuntado sería correcta? Gracias.

Pablo, no se trata de que sea correcta o no. Se trata de que la idea que has planteado tienes que desarrollarla. Ya te he aceptado la primera, es la que vas a tener que desarrollar. ¿Que quieres tener la segunda en caos de atranque? La tendrás que desarrollar desde el principio. Esto no es un "ejercicio" o una "práctica". Estás sentando las bases para tu proyecto, que vas a desarrollar a lo largo del cuatrimestre.

2022-09-22 11:50 UTC, merged