[IV-22-23] Objetivo 4 PMP_IV
MauronMP/PMP_IV pull request #23
Opened 2022-11-09 15:22 UTC by MauronMP

2022-11-10 13:19 UTC, JJ requested changes
El problema principal es que tienes que seguir las mejores prácticas para colocar los ficheros y testearlos directamente sin notebook

2022-11-10 15:37 UTC, MauronMP commented
> El problema principal es que tienes que seguir las mejores prácticas para colocar los ficheros y testearlos directamente sin notebook

Ya he hecho que no se hagan los tests con los notebooks, si no en ficheros '.py', funcionando correctamente

2022-11-11 19:15 UTC, JJ requested changes
Os dije desde el principio que tenéis que implementar vosotros la lógica de negocio, para testear todo lo que necesitéis e incluir sólo las funciones que requiera vuestro proyecto. Por tanto, no puedes usar ni `pandas` ni `numpy`, al menos en este milestone, donde lo importante es que tengáis la funcionalidad adecuada. 
Además, CSV es una biblioteca core en Python, así que tampoco necesitar cargar con esas librerías sólo para leer un CSV.
La elección de herramientas parece adecuada, pero el desarrollo del código no ha seguido la metodología correcta.

2022-11-11 19:15 UTC, JJ commented on pmp_iv/segmentacionCSV/Datos.py
> +        self.df = pd.read_csv('data/incendiosForestales.csv')
Aparentemente, gran parte o todo este fichero está desarrollado refiriéndote a issues que hablan sólo de elegir bibliotecas.
Es funcionalidad nueva. Siendo así, tienes que crear issues y referirte a las HUs correspondientes.

2022-11-14 13:23 UTC, JJ requested changes
Aparte de las cosas adicionales que te comento, ¿filtrar es toda la parte de la lógica de negocio que vas a testear? ¿No habría que meter algo *realmente* de cálculo? Os advertí desde el principio que la lógica de negocio había que programarla, y testearla... En concreto, no parece que sólo filtrar satisfaga de alguna forma #7 o de qué forma contribuye al mismo.

2022-11-14 13:23 UTC, JJ commented on docs/Test_runner.md
> +- Seguridad.
¿Qué tiene que ver la seguridad con un test runner? ¿Cómo la mides?

2022-11-14 13:23 UTC, JJ commented on iv.yaml
> +  - tests/test_Jupyter.py
Este fichero ya no existe.

2022-11-14 13:23 UTC, JJ commented on tests/test_Datos.py
> +from hamcrest import *
Mira en errores frecuentes de la semana 10 lo que se dice sobre nombres de ficheros.

2022-11-14 13:23 UTC, JJ commented on pyproject.toml
> +matplotlib = "^3.6.2"
¿Esto lo estás usando en producción?

2022-11-14 13:23 UTC, JJ commented on pmp_iv/segmentacionCSV/Datos.py
> +    def diagramaDispersion(self,data,area,image_name):
Una clase "Datos" no puede incluir un diagrama de dispersión. Tampoco hay ninguna historia de usuario que lo pida, y menos para este milestone.
Si lo quieres usar para ilustrar el README.md, simplemente mételo en un subdirectorio con scripts, pero lo mejor sería mantenerlo fuera del repositorio (ya que no añade valor a ninguna historia de usuario y no lo estás testando)

2022-11-14 13:23 UTC, JJ commented on pmp_iv/segmentacionCSV/Datos.py
> +        with open('data/incendiosForestales.csv', 'r', newline='') as file:
¿En qué issue dice que necesitas saber el tamaño del CSV? Y, sobre todo, ¿por qué es esto una función y no se mete en el constructor?

2022-11-14 13:23 UTC, JJ commented on pmp_iv/segmentacionCSV/Datos.py
> +        with open('data/incendiosForestales.csv', 'r', newline='') as csvfile:
¿Estás abriendo el fichero en cada función?
¿Seguro que no necesitas plantear un problema en un issue sobre este tema?

2022-11-14 13:23 UTC, JJ commented on tests/test_Datos.py
> +    assert_that(Datos().size_of_CSV(), equal_to(517))
No debes usar literales en ningún test. En el momento que cambies el fichero esto va a petar.

2022-11-16 06:24 UTC, JJ requested changes
Por segunda vez, sólo se puede usar código propio en este objetivo, como se advirtió [*en el objetivo cero*](https://github.com/MauronMP/PMP_IV/pull/2#discussion_r976166821)

2022-11-16 06:24 UTC, JJ commented on pmp_iv/forest_prediction/eda.py
> +        all_propierties = []
typo: propierties

2022-11-16 06:24 UTC, JJ commented on pmp_iv/forest_prediction/model_building.py
> +from sklearn.preprocessing import StandardScaler
¿Qué parte de "sólo puedes usar código propio" no has entendido?

2022-11-17 10:51 UTC, MauronMP commented
@JJ

2022-11-18 06:40 UTC, JJ requested changes
Ninguna de las objeciones es grave, pero acumuladas dejan el código en un estado que podría no ser adecuado para progresar a las siguientes fases.
Adicionalmente, no has puesto explícitamente los criterios que has usado para primero buscar y luego seleccionar ninguna de las herramientas, de acuerdo con lo que explicamos en clase. Implícitamente parece que estás usando la puntuación de snyk, pero no parece que eso sólo deba ser un criterio.

2022-11-18 06:40 UTC, JJ commented on tasks.py
> +def jupyter(c):
Esto ya no lo necesitas

2022-11-18 06:40 UTC, JJ commented on pmp_iv/forest_prediction/correlacion_area.py
> +class correlacion_dato_area():
Por favor, infórmate y sigue las buenas prácticas. Para empezar, la clase y el fichero deberían llamarse igual.
Una clase siempre se llama por los datos que contiene, no por lo que hace.

2022-11-18 06:40 UTC, JJ commented on pmp_iv/forest_prediction/correlacion_area.py
> +    def calculo_coeficiente(self):
Estás haciendo un montón de cálculos sobre algo que no varía, puesto que se lee de un fichero.

2022-11-18 06:40 UTC, JJ commented on pmp_iv/forest_prediction/correlacion_area.py
> +        self.X = EDA().by_property(propiedad)
¿Estás leyendo el mismo fichero 2 veces?

2022-11-18 06:40 UTC, JJ commented on tests/test_pmp_iv.py
> +import pmp_iv.enums.day
Sigue sin ser una buena práctica esta organización del repositorio, ya te lo dije.

2022-11-18 06:40 UTC, JJ commented on tests/test_pmp_iv.py
> +    filtrado_mes = EDA().by_date_property(MES_AGOSTO,DIA_LUNES)
Estás leyendo EDA múltiples veces. Deberías intentar usar las tres fases; Arrange, Act and Assert, y leer todo lo necesario (en Python se les llama Fixtures) en una primera fase (todas las bibliotecas de aserciones lo tienen)

2022-11-21 11:12 UTC, MauronMP commented
Buenas @JJ, el test usa fixtures, Arrange, Act and Assert. He actualizado el directorio pmp_iv/ y no creo varias instancias de la clase EDA. Solicito revisión.

2022-11-21 11:33 UTC, JJ requested changes
El objetivo 4 estaría bien, pero ahora no está bien el 3. Tienes que poner una tarea que compruebe la sintaxis.

2022-11-21 11:33 UTC, JJ commented on pmp_iv/models/coordenada.py
> +from pmp_iv.validaciones.validation import Validation
Una vez más, la jerarquía de ficheros debe reflejar la de objetos. No veo por qué no tienen que estar estos en el directorio principal, incluso en el mismo fichero.

2022-11-21 11:33 UTC, JJ commented on pmp_iv/models/correlacion_area.py
> +        cuadrado_x = 0
Ninguna de estas funciones son pesadas como para "retrasar" su uso. Poniéndolas en una función estás forzando a que se llamen múltiples veces, en vez de simplemente calcularlas en el momento que estén los datos disponibles, que es en la construcción.

2022-11-21 11:33 UTC, JJ commented on pmp_iv/models/eda.py
> +    def get_data_values(self):
Igual que antes, mira errores frecuentes semana 11

2022-11-21 11:33 UTC, JJ commented on pmp_iv/models/eda.py
> +        for i in self.valores:
Debes tratar de evitar los bucles for todo lo posible. Usa `map` o `filter` o construcciones similares.

2022-11-21 11:33 UTC, JJ commented on pmp_iv/models/fecha.py
> +from pmp_iv.models.day import Day
Una vez más, esto no es una arquitectura MVC. Si no es un modelo de datos, no lo metas en un subdirectorio `models`. De hecho, no lo metas en *ningún* subdirectorio, como te he dicho antes.

2022-11-21 11:33 UTC, JJ commented on tasks.py
> +    run("poetry check")
Esto ya te lo dije: `poetry check` no comprueba la sintaxis.
Esto no sé como te lo dejé pasar en #19 . Cupongo que lo habrás añadido ahora porque te dio error, porque borraste el que tenías originalmente.

2022-11-21 13:11 UTC, MauronMP commented
Buenas @JJ, con inv check ya comprueba la sintaxis, el constructor de la correlación obtiene el cálculo directamente y uso map en la clase EDA, la verdad que está muy bien los cambios que me ha dicho, el test ha pasado de estar 10 segundos a 0.04s. Solicito revisión

2022-11-21 13:16 UTC, JJ approved these changes
:+1:

2022-11-21 13:53 UTC, merged