[IV-22-23] Objetivo 1 de Pablo Morenilla
MauronMP/PMP_IV pull request #4
Opened 2022-09-22 17:09 UTC by MauronMP

2022-09-25 17:59 UTC, JJ requested changes
Por favor, revisa bien el concepto de HU y el de milestone, aunque una de las HUs es salvable con un mínimo cambio.

2022-09-25 17:59 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[HU0] Como usuario quiero saber qué posibilidad hay que de haya un incendio.](https://github.com/MauronMP/PMP_IV/issues/5).
Las HU sólo están en el dominio del problema. "Saber la probabilidad" es la solución que tú propones.

2022-09-25 17:59 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[HU1] Como usuario, quiero estar notificado en caso de que haya un riesgo alto.](https://github.com/MauronMP/PMP_IV/issues/6).
Notificaciones son detalles de implementación que tampoco están en el dominio dle problema.

2022-09-25 17:59 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M0] Generar un csv.](https://github.com/MauronMP/PMP_IV/milestone/1).
Es una función, no un producto.

2022-09-25 17:59 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M1] Crear clase coordenada, fecha, FWI, temperatura, humedad, viento, lluvia y superficie.](https://github.com/MauronMP/PMP_IV/milestone/2).
Una tarea, no un producto.

2022-09-26 21:02 UTC, MauronMP commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M1] Crear clase coordenada, fecha, FWI, temperatura, humedad, viento, lluvia y superficie.](https://github.com/MauronMP/PMP_IV/milestone/2).
Buenas tardes, perdone que a lo mejor me he explicado mal, la idea en el milestone 0 es crear una clase que genere un CSV con esas cabeceras sin datos y en el caso del milestone 1, es crear esa estructura de datos para poder usarla a posteriori, no sé si entonces lo estoy entendiendo mal.

2022-09-27 08:59 UTC, MauronMP commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M1] Crear clase coordenada, fecha, FWI, temperatura, humedad, viento, lluvia y superficie.](https://github.com/MauronMP/PMP_IV/milestone/2).
Buenas, efectivamente lo entendía mal, perdone, corregiré los milestone de nuevo

2022-09-27 10:15 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M1] Crear clase coordenada, fecha, FWI, temperatura, humedad, viento, lluvia y superficie.](https://github.com/MauronMP/PMP_IV/milestone/2).
En el milestone 0 tampoco puedes tener ninguna lógica de negocio. Revisa, por favor, los milestones recomendados.

2022-09-27 11:26 UTC, JJ requested changes
Por favor, trata de entender mejor
* El problema, qué modelo vas a usar, y qué lógica de negocio necesitaría.
* Quién va a ser cliente del problema (generalmente, quien pueda hacer algo al respecto)
* Qué es la nube y por qué este producto tendría que estar en la nube y no en un simple servidor que se conecte a Internet para bajarse los datos.
* Finalmente, entender que los milestones son productos progresivamente más complejos, etapas en la comprensión y la satisfacción de las necesidades del cliente. Tienes que entender cuales son esos hitos del desarrollo, qué vas a ofrecer y qué product cierra a cuál.

2022-09-27 11:26 UTC, JJ commented on README.md
> +Un software capaz de predecir a lo largo del día, semana(no sé ciertamente si es posible predecir una semana), el porcentaje de riesgo de incendio en la zona en la que esté el cliente final.
¿Y a lo largo de un día sí lo sabes?

2022-09-27 11:26 UTC, JJ commented on doc/Comprobaciones/0_Requisitos.md
> +    Si, puesto que trata el tema de incendios y es un tema que repercute y ocurre en toda la zona de España, por ejemplo el incendio que hubo en Granada recientemente.
Aquí deberías contestar si sabes dónde obtener los datos y cómo procesarlos, no esto, que ya se supone que sí. También que sepas validar la solución o conozcas a una persona que lo haga.

2022-09-27 11:26 UTC, JJ commented on doc/Comprobaciones/0_Requisitos.md
> +    Sí, no puede estar centralizado, ya que la idea es distribuirlo a clientes finales como ganaderos, agricultores y residentes.
Los clientes finales no son la nube. Por favor, trata de consultar qué es lo que se entiende por una aplicación en la nube.

2022-09-27 11:26 UTC, JJ commented on doc/Comprobaciones/0_Requisitos.md
> +    Si, ya que se necesita realizar una serie de cálculos, transformación de los datos y acotarlos a las zonas de los clientes, no es un "almacena y busca" como tal.
La respuesta a esta pregunta requiere que explicites esa "serie de cálculos" y compruebes que tienes un modelo del problema y todos los datos para llevarlos a cabo. Me temo que esto vas a tener que decirlo tarde o temprano, y si no lo dices claramente es complicado que pases al siguiente objetivo.

2022-09-27 11:26 UTC, JJ commented on doc/Comprobaciones/1_Comprobacion_HU.md
> +## Comprobaciones en las historias de usuarios
Esto debería ir en el cuerpo del PR.

2022-09-27 11:26 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[HU0] Como usuario residente en zonas forestales, necesitaría estar informado de los riesgos de incendio que puede haber donde vivo.](https://github.com/MauronMP/PMP_IV/issues/5).
OK, esta HU en primera lectura, podría ser válida. Pero como te he dicho antes, "donde vivo" y "riesgos" tienes que tenerlo muy bien modelizado. Y al final no sé muy bien esto qué problema resuelve. Suponte que el problema calcula un 90% de riesgo de incendio "donde vivo". ¿Qué puede hacer al respecto? ¿De qué sirve que lo sepa él y no las autoridades? ¿Le resuelve algún problema o le reporta algún beneficio?

2022-09-27 11:26 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[HU1] Como usuario, quiero saber si pudiera haber un incendio, para poder tener tiempo de reacción.](https://github.com/MauronMP/PMP_IV/issues/6).
¿En qué se diferencia de la anterior?
¿De veras crees que algo te puede decir si va a haber "un incendio"?

2022-09-27 11:26 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M0] Función generador de ficheros en formato de tablas vacias.](https://github.com/MauronMP/PMP_IV/milestone/1).
??? No sé qué tiene que ver esto con nada. Una función tampoco es un PMV.

2022-09-27 11:26 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M1] Estructura de datos para poder manejar los distintos parámetros posibles a la hora de hacer un estudio de los incendios.](https://github.com/MauronMP/PMP_IV/milestone/2).
¿De dónde obtienes estos "parámetros"?

2022-09-27 11:26 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M2] Estructura de datos acorde al milestone M0.](https://github.com/MauronMP/PMP_IV/milestone/3).
¿Qué es "acorde a"?

2022-09-28 17:40 UTC, JJ requested changes
Sigue habiendo problemas
1. No creo que el cliente esté bien definido. Si se resuelve el problema, tiene que poder hacerse algo al respecto. Tienes bien identificados los factores, si esos factores te proveen con alguna acción, sólo va a poder ejecutar esa acción la administración.
2. Debes diseñar un producto mínimamente viable que no dependa de una IA. Dado que extraer información de un formato determinado es una lógica de negocio aceptable, podría ir por ahí.
3. Los milestones son productos mínimamente viables, y debes diseñarlos de forma que unos dependan de otros. No necesitas los datos para programar; necesitas *el formato* de los datos y los rangos, por ejemplo.

2022-09-28 17:40 UTC, JJ commented on doc/Comprobaciones/0_Requisitos.md
> +    Si, para poder trabajar y entrenar a una IA con deep learning se usarán datos de un csv recogido de los incendios ocurridos en la zona norte de [Portugal](http://archive.ics.uci.edu/ml/datasets/F
Piénsate bien lo de la IA con deep learning. Insisto, *tenéis que programarlo vosotros* y preparar los tests de forma que comprueben que se hace la predicción correctamente.

2022-09-28 17:40 UTC, JJ commented on doc/Comprobaciones/1_Comprobacion_HU.md
> +## Comprobaciones en las historias de usuarios
:arrow_up:

2022-09-28 17:40 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[HU0] Como usuario residente en zonas forestales, necesitaría estar informado de los riesgos de incendio que puede haber donde vivo.](https://github.com/MauronMP/PMP_IV/issues/6).
Insisto, no creo que el  residente de zonas forestales sea el cliente de esta aplicación. No saben interpretar los riesgos, ni pueden hacer nada al respecto. Tampoco "donde vivo" es un concepto que tenga una formulación precisa.

2022-09-28 17:40 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M1] Recoger datos.](https://github.com/MauronMP/PMP_IV/milestone/4).
Son tareas, no productos mínimamente viables.

2022-09-28 17:40 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M2] Entrenar una IA.](https://github.com/MauronMP/PMP_IV/milestone/5).
Insisto, no creo que una IA pueda ser un producto mínimamente viables para este proyecto. Y también es una tarea.

2022-09-29 18:31 UTC, JJ requested changes
No sé si has cambiado sólo las HUs en GitHub, pero el texto no ha cambiado excesivamente ni has reflejado lo que hemos hablado esta mañana.

2022-09-29 18:31 UTC, JJ commented on doc/Comprobaciones/1_Comprobacion_HU.md
> +## Comprobaciones en las historias de usuarios
Podías haberlo borrado de aquí...

2022-09-29 18:31 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[HU0] Como usuario residente en zonas forestales, necesitaría estar informado de los riesgos de incendio que puede haber donde vivo.](https://github.com/MauronMP/PMP_IV/issues/6).
¿Esto no hemos hablado que lo ibas a cambiar?

2022-09-29 18:31 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[M2] Obtención de un nivel de riesgo en la escala de INFOEX.](https://github.com/MauronMP/PMP_IV/milestone/8)
Especifica el producto que vaya a obtener ese nivel de riesgos.

2022-09-29 18:39 UTC, MauronMP commented
> No sé si has cambiado sólo las HUs en GitHub, pero el texto no ha cambiado excesivamente ni has reflejado lo que hemos hablado esta mañana.

Cierto, perdone. Lo rectifico

2022-09-30 08:04 UTC, MauronMP commented
> > No sé si has cambiado sólo las HUs en GitHub, pero el texto no ha cambiado excesivamente ni has reflejado lo que hemos hablado esta mañana.
> 
> Cierto, perdone. Lo rectifico

He indicado el producto final y cambiado el cliente

2022-09-30 08:56 UTC, arsa-dev commented
Hola @MauronMP, ojeando un poco la historia de usuario, he observado que la tienes asignada al M2, sin embargo, ya que este milestone depende de M1 y M0 respectivamente, y estos aún no están terminados, lo óptimo sería asignar la historia de usuario al M0, ya que un milestone en curso siempre busca generar un PMV (aunque no sea usable por el usuario final, como por ejemplo la estructura de datos) y debe de tener asociada una historia de usuario para la cual se está desarrollando ese PMV.

2022-09-30 11:39 UTC, JJ approved these changes
Más o menos, está superado. Necesitarás trabajar un poco más cuales son los usuarios y posiblemente añadir otra historia de usuario. En el siguiente objetivo, @arsa-dev se encargará de llevarlo a cabo en este repositorio.

2022-09-30 11:39 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[H0] Como usuario, quiero conocer el nivel de riesgo de incendio.](https://github.com/MauronMP/PMP_IV/issues/7).
Deberías especificar un poco más los usuarios. Una cosa es que quites al guardabosques, otra que no pongas ninguno.

2022-09-30 11:39 UTC, JJ commented on doc/HistoriasUsuarios_Hitos.md
> +   - [[H0] Como usuario, quiero conocer el nivel de riesgo de incendio.](https://github.com/MauronMP/PMP_IV/issues/7).
Además, también hemos hablado en clase otras cosas que podrías haber puesto, como el "analista de datos" del organismo encargado.

2022-10-14 08:17 UTC, merged